require("env")
require("variables")
require("config")
require("keybinds")
require("bind")
require("layer")
require("animation")
require("workspace")
require("tactile")
-- For Noctalia Color templates
require("noctalia").apply_theme()

hl.on("hyprland.start", function()
	hl.exec_cmd("dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP")
	hl.exec_cmd("hyprctl setcursor Bibata-Modern-Classic 24")
	hl.exec_cmd("noctalia")
end)
